### ISSUE TITLE
大佬，能否加上warp和网站分流到warp的功能？

### ISSUE THREAD

**Issue by lovelygfj** [fscarmen2/Argo-Xray-PaaS#3]
目的是尝试解锁netflix非自制剧
有些vps被限制了只能看自制，但套了warp以后，warp是ip就能看非自制。
谢谢

**Comment by fscarmen** [comment]
这些容器开不了tun，多数是用不了warp的

**Comment by lovelygfj** [comment]
我以为您脚本用的ARGO已经算是可以打开cloudflare的代理了呢。
技术上我也不太懂，我目前在Doprax上用这个脚本，还挺方便的。
反正如果能把奈飞分流到warp，多了一个解锁的可能性，就更好了，没有也没太大关系，现在也很好

**Comment by fscarmen** [comment]
> 我以为您脚本用的ARGO已经算是可以打开cloudflare的代理了呢。
原来不一样的，warp处理的是出口，而这个argo是入口来的，就是你--->CF 优选IP--->CF argo--->容器--->xray 原生接口出局

我们想要的效果是
你--->。。。。。--->容器--->xray---> Netflix warp 出局
。。。。。。。。。。。。。。。 |-----> 其他用原生接口出局
                   
要找个时间试试wireproxy是否可以支持，但要到周末了。

**Comment by lovelygfj** [comment]
感谢大佬
大佬注意身体
不是特别重要的需求
很有可能套上了cloudflare warp的IP以后发现奈飞依然封锁了这个IP，不让看自制剧 :-)
