### ISSUE TITLE
back4app部署80端口的问题【20230430部署】

### ISSUE THREAD

**Issue by xzchsia** [fscarmen2/Argo-Xray-PaaS#5]
back4app部署80端口的问题【20230430部署】
一直提示。

trying to hit the 80 port using http
it looks that no process is listening to the 80 port using http

最后提示部署失败，请问大佬这个有没有办法解决。谢谢

**Comment by PikachuJP** [comment]
Use raw code without .github/workflow folder in it also it will active after 5 time retrying if you do it right

**Comment by PikachuJP** [comment]
just these files
![image](https://user-images.githubusercontent.com/128409341/235370755-02596091-d5db-488d-8d5d-ece4685052dd.png)

**Comment by xzchsia** [comment]
thanks, i will try it.
