### ISSUE TITLE
koyeb无法使用

### ISSUE THREAD

**Issue by paopaomalin** [fscarmen2/Argo-Xray-PaaS#8]
![image](https://github.com/fscarmen2/Argo-Xray-PaaS/assets/95903329/b2f4dc5f-1d29-4055-87b7-c2a37d3c5a67)

**Comment by fscarmen** [comment]
本项目停更了，可以关注此项目 https://github.com/mjjonone/mjj

**Comment by fscarmen2** [comment]
本项目停更了，可以关注此项目 https://github.com/mjjonone/mjj
